name: Fetch TGVmax CSV daily

on:
  schedule:
    - cron: "2 13 * * *"
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
      EXPORT_URL: "https://ressources.data.sncf.com/api/explore/v2.1/catalog/datasets/tgvmax/exports/csv?select=*&order_by=date&limit=100000"
    steps:
      - uses: actions/checkout@v4

      - name: Make dirs
        run: mkdir -p snapshots

      - name: Download CSV (with retries)
        run: |
          TS=$(date +'%Y-%m-%d')
          for i in 1 2 3; do
            curl -fL --retry 3 --retry-delay 5 "$EXPORT_URL" -o "snapshots/tgvmax_${TS}.csv" && break || sleep 10
          done
          test -s "snapshots/tgvmax_${TS}.csv"

      - name: Commit if changed
        run: |
          git config user.name "tgvmax-bot"
          git config user.email "tgvmax-bot@users.noreply.github.com"
          git add snapshots/
          git commit -m "snapshot: ${TZ} $(date '+%Y-%m-%d %H:%M:%S %Z')" || echo "No changes"
          git push
